# Generated by Django 2.2.6 on 2019-10-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedcategory',
            name='category',
            field=models.CharField(choices=[('Shopping', 'Shopping'), ('Food & Drink', 'Food & Drink'), ('Groceries', 'Groceries'), ('Entertainment', 'Entertainment'), ('Others', 'Others')], default=None, max_length=12),
        ),
    ]
