# Generated by Django 2.2.6 on 2019-10-30 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191030_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('category', models.CharField(choices=[('Vacation', 'Vacation'), ('Trip', 'Trip'), ('Motorisation', 'Motorisation'), ('Trip', 'Trip'), ('Bussiness', 'Bussiness'), ('Others', 'Others')], default=None, max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
