# Generated by Django 2.2.6 on 2019-10-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
