# Generated by Django 2.2.6 on 2019-10-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_saving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='category',
            field=models.CharField(choices=[('Vacation', 'Vacation'), ('Trip', 'Trip'), ('Motorisation', 'Motorisation'), ('Trip', 'Trip'), ('Business', 'Business'), ('Others', 'Others')], default=None, max_length=12),
        ),
    ]
