# Generated by Django 2.2.6 on 2019-11-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191031_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='category',
            field=models.CharField(choices=[('Shopping', 'Shopping'), ('Food & Drink', 'Food & Drink'), ('Groceries', 'Groceries'), ('Entertainment', 'Entertainment'), ('Bill', 'Bill'), ('Subscription', 'Subscription'), ('Income', 'Income'), ('Saving', 'Saving'), ('Others', 'Others')], default=None, max_length=255),
        ),
    ]
