# Generated by Django 2.2 on 2019-10-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191021_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='category',
            field=models.CharField(choices=[('Shopping', 'Shopping'), ('Food & Drink', 'Food & Drink'), ('Groceries', 'Groceries'), ('Entertainment', 'Entertainment'), ('Bill', 'Bill'), ('Subscription', 'Subscription')], default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='operation',
            name='method',
            field=models.CharField(default='Bank transfer', max_length=255),
        ),
    ]
