# Generated by Django 2.2 on 2019-10-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191021_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='add_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
