# Generated by Django 2.2 on 2019-10-22 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191021_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='category',
            field=models.CharField(choices=[('Shopping', 'Shopping'), ('Food & Drink', 'Food & Drink'), ('Groceries', 'Groceries'), ('Entertainment', 'Entertainment'), ('Bill', 'Bill'), ('Subscription', 'Subscription'), ('Income', 'Income'), ('Others', 'Others')], default=None, max_length=255),
        ),
        migrations.CreateModel(
            name='ReccuringPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('paid_until', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('category', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
