# Generated by Django 2.2.6 on 2019-11-01 01:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reccuringpayment_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reccuringpayment',
            name='paid_until',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
