# Generated by Django 2.2.6 on 2019-11-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191101_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reccuringpayment',
            name='category',
            field=models.CharField(choices=[('Bill', 'Bill'), ('Subscription', 'Subscription')], max_length=12),
        ),
    ]
